### ISSUE TITLE
AttributeError: 'datetime.date' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by Gidrek** [pallets/werkzeug#695]
I was working in Python 3 to generate my atom feed and I got the error.

```
AttributeError: 'datetime.date' object has no attribute 'tzinfo'
```

I have fixed adding the next code to werkzeug/contrib/atom.py file

```
from datetime import datetime, time


def format_iso8601(obj):
    """Format a datetime object for iso8601"""
    iso8601 = obj.isoformat()
    obj = datetime.combine(obj, time())
    if obj.tzinfo:
          return iso8601
   return iso8601 + 'Z'
```

And the atom feed was working fine.

**Comment by homeworkprod** [comment]
I'm seeing this as well on Python 3.4.2, but it has been working on Python 3.4 before.

The breaking change is b27aec1cd45cce8b50430bf28e9f05feb49320c6 and it was released with Werkzeug 0.10. Not sure how it slipped through, though.

**Comment by untitaker** [comment]
I'm going to treat this as regression, but there doesn't seem to be anything in the docs that says `date` objects are accepted.

**Comment by homeworkprod** [comment]
Fair enough.

However, the docs do explicitly state that a `datetime.datetime` instance should be passed, and they do so at least for a few years. Then again, I wrote my code some more years ago and probably didn't check the relevant docs since.

That said, accepting `date` probably isn't a good idea because the Atom syndication format standard [defines dates as containing both a date and a time](http://tools.ietf.org/html/rfc4287#section-3.3).

So, before the Werkzeug module implicitly adds any time part (maybe midnight – which itself isn't always `00:00:00`, but that's another story – but definitively not the current time) itself, requiring a `datetime` object and throwing an exception if not given seems the better approach to me.

The workaround above as posted by @Gidrek does, as a result, seem to omit the time part in the output completely and, thus, would violate the spec (if I'm not mistaken).

**Comment by homeworkprod** [comment]
Looks like using midnight as the time part when a `date` is given is what previously happened, but I would favor explicitness here (i. e. requiring the user to add the time part beforehand).

**Comment by untitaker** [comment]
So, what is the preferred resolution of this? It seems to me that if 0.10's
behavior is correct, it wouldn't make sense to correct it again...

**Comment by homeworkprod** [comment]
@untitaker, I'd say that not accepting `date` instances is the right thing to do, but I'd favor an explicit guard and exception to make things clear – especially considering that `date` instances had been excepted before.

**Comment by Gidrek** [comment]
It's working fine.

I had an error. I am building a static generator page and I sent the just the date. I added the hours, minutes and seconds and now is working.
