### ISSUE TITLE
Cannot import using python 3.10

### ISSUE THREAD

**Issue by EdmundsEcho** [pallets/werkzeug#2754]
Hello, I've been using this package indirectly for years.  Thank you!

When importing the package, I get the following exception.  This is with package version: 2.3.6 (per what is in the `__init__.py`) and python 3.10.  I suspect this was not an issue with python 3.8 where I had things working beautifully.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/venv/lib/python3.10/site-packages/werkzeug/__init__.py", line 2, in <module>
    from .test import Client as Client
  File "/opt/venv/lib/python3.10/site-packages/werkzeug/test.py", line 35, in <module>
    from .sansio.multipart import Data
  File "/opt/venv/lib/python3.10/site-packages/werkzeug/sansio/multipart.py", line 19, in <module>
    class Preamble(Event):
  File "/usr/local/lib/python3.10/dataclasses.py", line 1175, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/usr/local/lib/python3.10/dataclasses.py", line 1093, in _process_class
    str(inspect.signature(cls)).replace(' -> None', ''))
AttributeError: module 'inspect' has no attribute 'signature'
```

**Comment by davidism** [comment]
You'll notice the last file in the traceback is Python's dataclasses module, not us. This suggest an error with your installation of Python, or perhaps the current virtualenv. This isn't something we can help you debug, sorry. Werkzeug does work in Python 3.10, as you can see in CI runs for commits.

**Comment by EdmundsEcho** [comment]
I came back to github the minute I realized that `inspect` is an issue as you described.  Thank you for the quick assessment.
