### ISSUE TITLE
DebugApplication(..., pin_security=False) no longer works

### ISSUE THREAD

**Issue by living180** [pallets/werkzeug#3075]
Starting with werkzeug 3.1.4, passing `pin_security=False` to `DebugApplication()` raises an exception:

```
from django.core.wsgi import get_wsgi_application

from werkzeug.debug import DebuggedApplication

application = DebuggedApplication(get_wsgi_application(), evalex=True, pin_security=False)
```

```
  File "/home/<redacted>/code/<redacted>/wsgi.py", line 6, in <module>
    application = DebuggedApplication(get_wsgi_application(), evalex=True, pin_security=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<redacted>/.virtualenvs/<redacted>/lib/python3.12/site-packages/werkzeug/debug/__init__.py", line 303, in _
_init__
    self.pin = None
    ^^^^^^^^
  File "/home/<redacted>/.virtualenvs/<redacted>/lib/python3.12/site-packages/werkzeug/debug/__init__.py", line 323, in p
in
    del self._pin
        ^^^^^^^^^
AttributeError: 'DebuggedApplication' object has no attribute '_pin'
```

Environment:

- Python version:  3.12
- Werkzeug version:  3.1.4

Appears to have been introduced by https://github.com/pallets/werkzeug/commit/0c49ff0649ded8b587dc7323a5e47dfffcabc3bc#diff-83867b1c4c9b75c728654ed284dc98f7c8d4e8bd682fc31b977d122dd045178a
