### ISSUE TITLE
Werkzeug 0.11.13 : Cannot import module SocketServer + name ForkingMixIn on Python 3.6(+Win10)

### ISSUE THREAD

**Issue by jmzoda** [pallets/werkzeug#1058]
Hello,
I have a flask application that works fine on Python 3.5.2 + Windows 10 but the errors below appear on Python 3.6 
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 65, in <module>
    from SocketServer import ThreadingMixIn, ForkingMixIn
ModuleNotFoundError: No module named 'SocketServer'

I changed the class SocketServer to lowercase in file serving.py, just like below 
try:
    from socketserver import ThreadingMixIn, ForkingMixIn

But another error appears and I cannot import ForkingMixIn
  File "C:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 65, in <module>
    from socketserver import ThreadingMixIn, ForkingMixIn
ImportError: cannot import name 'ForkingMixIn'

If you take a look at file c:\Program Files\Python36\Lib\socketserver.py at line 543 and 
If you compare socketserver.py on python 3.6 and 3.5, you see a new os attribute check, see below.
if hasattr(os, "fork"):   <<<<<<<<<<<<<<<<<< NEW in Python 3.6 which is false  
    class ForkingMixIn:
        # no class object created + no code because of hasattr(os, "fork") equals False

Again, this appears on Werkzeug 0.11.13 and Python 3.6.

Thank you

**Comment by untitaker** [comment]
Duplicate of #999

**Comment by Bilal-Khan15** [comment]
I got the same problem, which was resolved by uninstalling and installing the Flask and Werkzeug again

1) pip uninstall Flask
2) pip uninstall Werkzeug

3) pip install Flask
4) pip install Werkzeug
