### PR TITLE
Make socket.AF_UNIX compatible with Windows

### LINKED ISSUE #1353: master (0.15.dev) is broken on Windows
To reproduce, run the example from the readme:

```python
from werkzeug.wrappers import Request, Response

@Request.application
def application(request):
    return Response('Hello, World!')

if __name__ == '__main__':
    from werkzeug.serving import run_simple
    run_simple('localhost', 4000, application)
```

On Windows, I get the following error:
```
Traceback (most recent call last):
  File "zzz.py", line 11, in <module>
    run_simple('localhost', 4000, application)
  File "...\werkzeug\serving.py", line 880, in run_simple
    inner()
  File "...\werkzeug\serving.py", line 836, in inner
    fd=fd)
  File "...\werkzeug\serving.py", line 723, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "...\werkzeug\serving.py", line 624, in __init__
    server_address = get_sockaddr(host, int(port), self.address_family)
  File "...\werkzeug\serving.py", line 593, in get_sockaddr
    if family == socket.AF_UNIX:
AttributeError: module 'socket' has no attribute 'AF_UNIX'
```

It seems it was broken in https://github.com/pallets/werkzeug/commit/d2140a4b9a4f0b9c9afc0a2fbff55acb5399eec6#diff-5561c422f09af0c38ec8260f0d17a52dR593
(merged in #1019)

------

Version info:
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Werkzeug 0.15.dev (d2140a4 and later)

### PR DESCRIPTION
**Pull request by greyli**
Fix #1353

### CODE REVIEW

File: werkzeug/serving.py [hunk 1]
```diff
@@ -820,7 +825,7 @@ def run_simple(hostname, port, application, use_reloader=False,
     def log_startup(sock):
         display_hostname = hostname not in ('', '*') and hostname or 'localhost'
         quit_msg = '(Press CTRL+C to quit)'
-        if sock.family is socket.AF_UNIX:
+        if sock.family is af_unix:
```
[the remark this answers is not in the document]
Comment (greyli) [reply werkzeug/serving.py]: Done.

**Comment by greyli** [comment]
The failed test in pypy seems unrelated with last commit:
```pytb
=================================== FAILURES ===================================
___________________ TestMemcachedCache.test_generic_timeout ____________________
self = <test_cache.TestMemcachedCache object at 0x0000000009170a68>
c = <werkzeug.contrib.cache.MemcachedCache object at 0x0000000009170d78>
fast_sleep = <built-in function sleep>
    def test_generic_timeout(self, c, fast_sleep):
        c.set('foo', 'bar', 0)
        assert c.get('foo') == 'bar'
        c.set('baz', 'qux', 1)
>       assert c.get('baz') == 'qux'
E       AssertionError: assert None == 'qux'
E        +  where None = <bound method MemcachedCache.get of <werkzeug.contrib.cache.MemcachedCache object at 0x0000000009170d78>>('baz')
E        +    where <bound method MemcachedCache.get of <werkzeug.contrib.cache.MemcachedCache object at 0x0000000009170d78>> = <werkzeug.contrib.cache.MemcachedCache object at 0x0000000009170d78>.get
tests/contrib/cache/test_cache.py:130: AssertionError
```

**Comment by greyli** [comment]
Can we merge this?
